apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: testrgstr.azurecr.io/azure29042022:1
          ports:
            - containerPort: 8072
          env:
          - name: DOCKER_ENV
            value: "dev"

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argo-demo
  name: argo-demo
  namespace: argocd
spec:
  ports:
  - name: http
    port: 8072
    protocol: TCP
    targetPort: http
  selector:
    app: web
  sessionAffinity: None
  type: NodePort

---
