apiVersion: v1
kind: Namespace
metadata:
  name: newtool1
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
  namespace: newtool1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 440953937617.dkr.ecr.us-east-2.amazonaws.com/opsera-nexus-integrator:v2
          ports:
            - containerPort: 3000
          env:
            - name: DOCKER_ENV

